### ISSUE TITLE
Add note that this is outdated, point to React docs

### ISSUE THREAD

**Issue by saarw** [microsoft/TypeScript-React-Conversion-Guide#21]
These old tutorials should include a note to the React documentation where Typescript is now easily added through a simple npm install
https://facebook.github.io/create-react-app/docs/adding-typescript

**Comment by gboy666** [comment]
I think it's still useful for projects not created using CRA.

**Comment by gardner** [comment]
`awesome-typescript-loader` was last published three years ago. This repo, being under the microsoft GitHub org, sent me down the wrong path.

**Comment by vonwao** [comment]
Yes, that's very disappointing that there's such outdated information here and no link to an updated tutorial

**Comment by orta** [comment]
I think there's some value in being able to understand how to do this without tooling like CRA/next etc, so I've given this repo a 2020 houseclean and I'm going to call this closed
