### ISSUE TITLE
README.md correction

### ISSUE THREAD

**Issue by thisislondon** [microsoft/TypeScript-React-Conversion-Guide#26]
Line 103 of README.md needs to be corrected to have **dist** removed, i.e. change from:
`    filename: './dist/bundle.js'`
to be:
`    filename: './bundle.js'`

This will now accurately match the intention, i.e. of having a copy-and-paste into README of [TicTacToe_TS/webpack.config.js](https://github.com/microsoft/TypeScript-React-Conversion-Guide/blob/master/TicTacToe_TS/webpack.config.js) for sensible build design.

Would be cool if you opened up access permissions on this repo to allow anyone to push a branch with a proposed fix, as then I'd have done so myself 😄 .

**Comment by DanielRosenwasser** [comment]
I just applied the change - thanks for the tip and sorry for the delay. We'll be archiving the repo now though, as we don't have the bandwidth to keep things up to date.
