### ISSUE TITLE
React 16

### ISSUE THREAD

**Issue by jimthedev** [microsoft/TypeScript-React-Conversion-Guide#4]
Is there any way to get typescript to show the correct line numbers in React 16? It seems like right now it is showing the error numbers from the JS and not the TSX?

Specifically ts-jest is the project having this issue.

**Comment by FDiskas** [comment]
Did you tried the "typescript-babel-jest" :rewind:

**Comment by orta** [comment]
I'm going to close this, I'd recommend looking at ts-jest or the jest docs for the answers 👍  

(given the amount of years it has been, I'd like to hope you found an answer before then )
