### ISSUE TITLE
Add exclude/include options to awesome-typescript-loader

### ISSUE THREAD

**Issue by vitalybe** [microsoft/TypeScript-React-Conversion-Guide#7]
Currently the loader would try to process node_modules as well, resulting in very slow compile times.

**Comment by khiitola** [comment]
I also followed the guide, and with a quite simple project my build times were several minutes. With this change it went down to 5 seconds:

```diff
--- a/webpack.config.js
+++ b/webpack.config.js
@@ -12,9 +12,9 @@ module.exports = {
   module: {
     rules: [
       // changed from { test: /\.jsx?$/, use: { loader: 'babel-loader' } },
-      { test: /\.(t|j)sx?$/, use: { loader: 'awesome-typescript-loader' } },
+      { test: /\.(t|j)sx?$/, exclude: /node_modules/, use: { loader: 'awesome-typescript-loader' } },
       // addition - add source-map support
-      { enforce: "pre", test: /\.js$/, loader: "source-map-loader" }    ],
+      { enforce: "pre", test: /\.js$/, exclude: /node_modules/, loader: "source-map-loader" }    ],
   },
   devServer: {
     historyApiFallback: true,
```

**Comment by jakegavin** [comment]
This caused a bit of friction for me when trying to get TypeScript working with an existing React project. I was stuck on an error `Error: Debug Failure. False expression` for a while. This went away when I realized I should be excluding node modules.

Would you be open to a PR that updates the docs? I'd be happy to do it. 

Thanks! This repo was helpful.
